apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: test-b909d49a-d3a2-41dd-8cd0
  namespace: demo
spec:
  params:
    - name: plan-name
      value: /audit/plans/coverage$
    - name: test-name
      value: ''
    - name: hw-target
      value: j784s4evm
    - name: testRunId
      #TODO: generate uuid
      value: b909d49a-d3a2-41dd-8cd0
    - name: testsRepo
      value: 'https://gitlab.cee.redhat.com/automotive/tests/all'
    - name: exporter-labels
      value:
        - board-type=j784s4evm
    - name: testBrunch
      value: main
    - name: client-name
      value: demo
    - name: timeout
      value: '691200'
    - name: ctx
      value: |-
        {
          "arch": "aarch64,image_name=qa,distro=rhel-9,polarion_report=on",
          "image_name": "qa",
          "distro": "rhel-9",
          "hw_target": "j784s4evm",
          "image_type": "regular",
          "scenario": "debug",
          "reserve_fresh": "off",
          "reserve_prepared": "off",
          "reserve_tested": "off",
          "polarion_report": "on"
        }
    - name: env
      value: |-
        {
          "TMT_SCRIPTS_DIR": "/usr/local/bin",
          "POLARION_URL": "https://polarion.engineering.redhat.com/polarion",
          "POLARION_REPO": "",
          "POLARION_USERNAME": "",
          "POLARION_PASSWORD": "",
          "POLARION_PROJECT": ""
        }
    - name: image-url
      #TODO: change to built image (deal with oras?)
      value: 'https://rhivos.auto-toolchain.redhat.com/in-vehicle-os-9/RHIVOS-1/latest-RHIVOS-1/TI/auto-osbuild-j784s4evm-rhivos-qa-regular-aarch64-10838681.aa225fe9.raw.xz'
    - name: skipProvisioning
      value: 'false'
  pipelineRef:
    name: test-pipeline
  taskRunTemplate:
    serviceAccountName: pipeline
  timeouts:
    pipeline: 1h0m0s
  workspaces:
    - name: jumpstarter-client-secret
      secret:
        secretName: demo-config
    - name: test-results
      persistentVolumeClaim:
        claimName: tmt-results
